(defun spacemacs/c++-rtags-takeover-flycheck ()
  (flycheck-mode)
  (flycheck-select-checker 'rtags)
  (setq-local flycheck-highlighting-mode nil)
  (setq-local flycheck-check-syntax-automatically nil))
